addons:
  sonarcloud:
    organization: "dtorun-github" # the key of the org you chose at step #3
    token:
      secure: "14517003fa3df2c5a705a65815a30bd032bfc5c7" # encrypted value of your token

#Test test
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
